[package]
name = "tft_analyzer"
version = "0.1.0"
authors = ["Kevin Shen <kevin_shen@hotmail.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
